set_mode:
  fields:
    mode:
      required: true
      selector:
        select:
          options:
            - value: idle_not_charging
              label: Idle (not charging)
            - value: idle_floating
              label: Idle (floating)
            - value: charging
              label: Charging
            - value: discharging
              label: Discharging
            - value: top_up
              label: Top up
    entry_id:
      required: false
      selector:
        text:
clear_override:
  fields:
    entry_id:
      required: false
      selector:
        text:
